# Generated by Django 4.1.3 on 2022-12-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(related_name='coursesinlanguage', to='courses.language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesinstatus', to='courses.status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesinsubject', to='courses.subject'),
        ),
    ]
