# Generated by Django 4.0.8 on 2022-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courselength',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
