# Generated by Django 4.0.8 on 2022-11-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='languages',
        ),
    ]
