# Generated by Django 4.0.8 on 2022-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_address2_user_country_user_locality_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
