# Generated by Django 4.0.8 on 2022-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_age_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='apt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ship_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
    ]
