# Generated by Django 4.0.8 on 2022-11-20 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid Phone Number', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
